'use client';

import { FormEvent, useEffect, useState } from 'react';
import { PublicSiteFooter, PublicSiteHeader } from './PublicSiteChrome';

type User = { name: string; email: string; role: string; cliente_id?: string };
type Project = { nombre_proyecto: string; estado: string; dias_entrega_estimados?: number };
const labels: Record<string, string> = { activa: 'Propuesta activa', enviada: 'Propuesta enviada', en_contrato: 'En contrato', pre_produccion: 'Preparando tu proyecto', produccion: 'En fabricación', entregado: 'Entregado', perdida: 'Propuesta no ganada', cancelada: 'Cancelado' };

export default function PublicAccount() {
  const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(true); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [projects, setProjects] = useState<Project[]>([]);
  const refresh = async () => { const result = await fetch('/api/auth/me'); const body = await result.json(); setUser(result.ok ? body.user : null); setLoading(false); };
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (user?.role !== 'cliente') return; fetch('/api/public/client-projects').then((response) => response.ok ? response.json() : { projects: [] }).then((body) => setProjects(body.projects ?? [])).catch(() => setProjects([])); }, [user]);
  const login = async (event: FormEvent) => { event.preventDefault(); setError(''); const response = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); if (!response.ok) { setError('No fue posible iniciar sesión.'); return; } await refresh(); };
  const logout = async () => { await fetch('/api/auth/logout', { method: 'POST' }); setProjects([]); setUser(null); };
  return <div className="min-h-screen bg-[hsl(var(--veta-bg-warm-paper))] text-[hsl(var(--veta-text-carbon))]"><PublicSiteHeader /><main className="veta-section px-6"><div className="mx-auto max-w-3xl">{loading ? <p className="text-sm">Cargando…</p> : !user ? <section className="veta-surface-glass mx-auto max-w-md rounded-[2rem] p-8"><h1 className="veta-heading text-3xl font-semibold">Mi cuenta</h1><form onSubmit={login} className="mt-6 space-y-4"><label className="block text-sm">Correo<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 block min-h-11 w-full rounded-xl border bg-white px-3" /></label><label className="block text-sm">Contraseña<input type="password" required value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1 block min-h-11 w-full rounded-xl border bg-white px-3" /></label>{error ? <p className="text-sm text-red-700">{error}</p> : null}<button className="min-h-11 rounded-full bg-[hsl(var(--veta-gold-muted))] px-5 text-xs font-semibold uppercase tracking-wider text-black">Ingresar</button></form></section> : user.role !== 'cliente' ? <section className="veta-surface-glass rounded-[2rem] p-8"><h1 className="veta-heading text-3xl font-semibold">Hola, {user.name}</h1><p className="mt-3 text-sm text-[hsl(var(--veta-text-stone))]">Tu espacio de trabajo está en la aplicación interna.</p><a href="/app/erp/comercial" className="mt-5 inline-block text-sm font-semibold">Ir al ERP</a><button onClick={logout} className="ml-5 text-sm underline">Cerrar sesión</button></section> : <section className="veta-surface-glass rounded-[2rem] p-8"><div className="flex items-center justify-between gap-4"><div><h1 className="veta-heading text-3xl font-semibold">Hola, {user.name}</h1><p className="mt-2 text-sm text-[hsl(var(--veta-text-stone))]">Aquí puedes ver el avance general de tus proyectos.</p></div><button onClick={logout} className="text-sm underline">Cerrar sesión</button></div><div className="mt-8 space-y-3">{projects.length ? projects.map((project, index) => <article key={`${project.nombre_proyecto}-${index}`} className="rounded-2xl border border-[hsl(var(--veta-glass-light-border))] p-5"><h2 className="font-semibold">{project.nombre_proyecto}</h2><p className="mt-1 text-sm text-[hsl(var(--veta-text-stone))]">{labels[project.estado] ?? project.estado}{project.dias_entrega_estimados ? ` · estimado ${project.dias_entrega_estimados} días` : ''}</p></article>) : <p className="text-sm text-[hsl(var(--veta-text-stone))]">No tienes proyectos asociados por ahora.</p>}</div></section>}</div></main><PublicSiteFooter /></div>;
}
